FROM docker.io/library/rust:1.94-slim-bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        pkg-config \
        libpcsclite-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup component add rustfmt clippy

WORKDIR /src

ENV CARGO_TERM_COLOR=always
